---
- hosts: 172.31.38.50
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: mytaskresult

  - name: i want to displays my task result
    debug: 
       msg: "{{mytaskresult}}"  

  - name: install git
    apt:
      name: git
      state: present
    when: mytaskresult.stderr ==""

  - name:
    apt:
      name: tree
      state: present
    when: mytaskresult.stderr !=""           