---
- hosts: 172.31.38.50
  become: yes
  tasks:
  - name: install git
    apt: 
      name: git
      state: present

  - name: install wget
    apt: 
      name: wget
      staterr: present
      ignore_errors: yes

  - name: install tree
    apt:
      name: tree
      state: present        