---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to install git on ubuntu
    apt:
      name: git
      state: present
    when: ansible_os_family =="Debian"

  - name:
    yum:
      name: git
      state: present
    when: ansible_os_family =="RedHat"   

  - name: i want to install server on ubuntu 
    apt:
      name: "{{myubuntupack}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to install server on Redhat
    yum:
      name: "{{myredhatpack}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start server 
    service:
       name: "{{myredhatpack}}"
       state: started
    when: ansible_os_family =="RedHat"       

  - name: i want to install tree on ubuntu
    apt:
      name: "{{mytreepack}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to install tree on Redhat
    yum:
      name: "{{mytreepack}}"
      state: present
    when: ansible_os_family =="RedHat"        

