---
- hosts: 172.31.38.50
  become: yes
  tasks:
  - name: git 
    apt: 
      name: git
      state: present
    tags: mygit


  - name: wget
    apt:
      name: wget
      state: present
    tags: mywget  

  - name: tree
    apt:
      name: tree
      state: present
    tags: mytree      